# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splashScreen = QtWidgets.QGraphicsView(self.centralwidget)
        self.splashScreen.setGeometry(QtCore.QRect(0, 0, 521, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splashScreen.sizePolicy().hasHeightForWidth())
        self.splashScreen.setSizePolicy(sizePolicy)
        self.splashScreen.setAcceptDrops(True)
        self.splashScreen.setWhatsThis("")
        self.splashScreen.setAutoFillBackground(True)
        self.splashScreen.setStyleSheet("QGraphicsView{\n"
"background-color:rgb(152, 255, 55);\n"
"}")
        self.splashScreen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splashScreen.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splashScreen.setInteractive(False)
        self.splashScreen.setObjectName("splashScreen")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 381, 491))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 530, 381, 141))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(8)
        font.setItalic(False)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(410, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setBold(True)
        font.setWeight(75)
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet("QPushButton{\n"
"      text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color:silver;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"}")
        self.sendButton.setObjectName("sendButton")
        self.channelButton = QtWidgets.QPushButton(self.centralwidget)
        self.channelButton.setGeometry(QtCore.QRect(400, 60, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setBold(True)
        font.setWeight(75)
        self.channelButton.setFont(font)
        self.channelButton.setStyleSheet("QPushButton{\n"
"      text-align: center;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color:silver;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"}")
        self.channelButton.setObjectName("channelButton")
        self.channelEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.channelEdit.setGeometry(QtCore.QRect(400, 30, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(True)
        font.setWeight(75)
        self.channelEdit.setFont(font)
        self.channelEdit.setObjectName("channelEdit")
        self.nameChannel = QtWidgets.QLabel(self.centralwidget)
        self.nameChannel.setGeometry(QtCore.QRect(10, 0, 371, 21))
        self.nameChannel.setObjectName("nameChannel")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(370, 29, 20, 491))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 320, 160, 99))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.passwordInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordInput.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(True)
        font.setWeight(75)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.gridLayout.addWidget(self.passwordInput, 2, 0, 1, 1)
        self.enterButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.enterButton.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(20)
        self.enterButton.setFont(font)
        self.enterButton.setObjectName("enterButton")
        self.gridLayout.addWidget(self.enterButton, 3, 0, 1, 1)
        self.usernameInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameInput.setMinimumSize(QtCore.QSize(158, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(True)
        font.setWeight(75)
        self.usernameInput.setFont(font)
        self.usernameInput.setStyleSheet("QGraphicsView{\n"
"background-img:\"Morelia_Logo_02-03.jpg\";\n"
"}")
        self.usernameInput.setObjectName("usernameInput")
        self.gridLayout.addWidget(self.usernameInput, 1, 0, 1, 1)
        self.textBrowser.raise_()
        self.textEdit.raise_()
        self.sendButton.raise_()
        self.channelButton.raise_()
        self.channelEdit.raise_()
        self.nameChannel.raise_()
        self.verticalScrollBar.raise_()
        self.splashScreen.raise_()
        self.gridLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuProfile = QtWidgets.QMenu(self.menuFile)
        self.menuProfile.setObjectName("menuProfile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionServer_settings = QtWidgets.QAction(MainWindow)
        self.actionServer_settings.setObjectName("actionServer_settings")
        self.menuProfile.addAction(self.actionServer_settings)
        self.menuFile.addAction(self.menuProfile.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MoreliaTalk"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "write your message..."))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.channelButton.setText(_translate("MainWindow", "change "))
        self.channelEdit.setPlaceholderText(_translate("MainWindow", "chanel"))
        self.nameChannel.setText(_translate("MainWindow", "TextLabel"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "password"))
        self.enterButton.setText(_translate("MainWindow", "Войти"))
        self.usernameInput.setPlaceholderText(_translate("MainWindow", "username"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProfile.setTitle(_translate("MainWindow", "Profile"))
        self.actionServer_settings.setText(_translate("MainWindow", "Server settings..."))
