# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.resize(246, 300)
        SettingsForm.setFocusPolicy(QtCore.Qt.TabFocus)
        SettingsForm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gridLayoutWidget = QtWidgets.QWidget(SettingsForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.saveButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 1, 1, 1)
        self.usernameInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.usernameInput.setObjectName("usernameInput")
        self.gridLayout.addWidget(self.usernameInput, 3, 1, 1, 1)
        self.serverLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout.addWidget(self.serverLabel, 0, 0, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 3, 0, 1, 1)
        self.passwordInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.passwordInput.setObjectName("passwordInput")
        self.gridLayout.addWidget(self.passwordInput, 4, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 4, 0, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout.addWidget(self.portLabel, 1, 0, 1, 1)
        self.serverInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.serverInput.setEnabled(True)
        self.serverInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.serverInput.setClearButtonEnabled(False)
        self.serverInput.setObjectName("serverInput")
        self.gridLayout.addWidget(self.serverInput, 0, 1, 1, 1)
        self.portInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.portInput.setFocusPolicy(QtCore.Qt.TabFocus)
        self.portInput.setObjectName("portInput")
        self.gridLayout.addWidget(self.portInput, 1, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancelButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.cancelButton.setAutoDefault(True)
        self.cancelButton.setFlat(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 6, 1, 1, 1)

        self.retranslateUi(SettingsForm)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "MoreliaTalk - Settings"))
        self.saveButton.setText(_translate("SettingsForm", "Save"))
        self.serverLabel.setText(_translate("SettingsForm", "Server"))
        self.usernameLabel.setText(_translate("SettingsForm", "Username"))
        self.passwordLabel.setText(_translate("SettingsForm", "Password"))
        self.portLabel.setText(_translate("SettingsForm", "Port"))
        self.serverInput.setToolTip(_translate("SettingsForm", "for example: http://example.com"))
        self.serverInput.setPlaceholderText(_translate("SettingsForm", "input server name"))
        self.portInput.setToolTip(_translate("SettingsForm", "for example: 80"))
        self.portInput.setPlaceholderText(_translate("SettingsForm", "input server port"))
        self.cancelButton.setText(_translate("SettingsForm", "Cancel"))
